[alembic]
# ...
sqlalchemy.url = sqlite:///social.db

[loggers]
keys=root,migrate

[handlers]
keys=console

[formatters]
keys=simple

[logger_root]
level=WARNING
handlers=console

[logger_migrate]
level=INFO
handlers=
qualname=migrate

[handler_console]
class=StreamHandler
level=NOTSET
formatter=simple
args=(sys.stdout,)

[formatter_simple]
format=%(levelname)-5.5s [%(name)s] %(message)s
datefmt=%H:%M:%S